feat: initial commit to add a helper method
aws-amplify/amplify-category-api pull request #1209
Opened 2023-01-30 07:59 UTC by manaswi223

#### Description of changes
This PR adds a utility helper method on RDS feature support for Amplify that converts the input graphql filter to the AWS RDS or mysql expressions that maps the fields in a schema type to a data source - AWS RDS resulting in a mySQL query.

For example:
A graphQL query passed as an input argument to the helper method `toRDSQueryExpressions` results a mapped mySQL query as shown below:

Input: ( a GraphQL query)

```
const inputVariables = {
  id: '1',
  name: 'Amplify',
  age: 20,
  address: {
    street: '123 Main St',
    city: 'Seattle',
    state: 'WA',
    zip: '98101',
  },
  filter : {  
    and: [      
      { eq: { id: '1' } },
      { startsWith: { name: 'Amplify' } }
    ],
  },
};
```

`const rdsQueryExpression = toRDSFilterExpression(inputVariables.filter);`

Output: (An RDS expression)

`id = 1 WHERE name = "Amplify%"`

##### CDK / CloudFormation Parameters Changed

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-01-31 18:16 UTC, sundersc commented on packages/amplify-graphql-model-transformer/src/resolvers/common.ts
> +          subExpressions.push(` between '${filterValue[0]}' and '${filterValue[1]}'`);
We should validate filterValue is an array and contains 2 elements.

2023-01-31 18:21 UTC, sundersc commented on packages/amplify-graphql-model-transformer/src/resolvers/common.ts
> +          const subExpression = toRDSFilterExpression(filterValue);
Can we add test cases for filters with 'and' and 'or' conditions?

2023-01-31 18:23 UTC, sundersc requested changes
Need tests with how we can chain these conditions with knex query.

2023-02-02 09:26 UTC, manaswi223 commented on packages/amplify-graphql-model-transformer/src/resolvers/common.ts
> +export const toRDSFilterExpression = (filter: any): string => {
< will add this code on RDS Lambda in next revision, waiting to get more context >

2023-02-02 10:44 UTC, manaswi223 commented
Todo:
1. Discuss `NOT` graphQL filter equivalent in RDS Query expression
2. Implement `size` 
3. Write test cases on knex: Test the resultant expression (output of the utility method) - `toRDSQueryExpression` as an input feed to the knex.js libraries & verify it to be in a Knex.js compatible format - agnostic to any DB engines.

2023-02-06 15:27 UTC, marcvberg commented
Before you commit, you'll need to run `yarn api-extract` to update the API.md files

2023-02-06 15:41 UTC, marcvberg commented
We can't build the queries by just substituting into strings/string concatenation, we'll have to use parameterization to block SQL injection on filter arguments 

`.fromRaw('(select * from "users" where "age" > ?)', '18')`

You can find docs on it [here](https://knexjs.org/guide/query-builder.html#fromraw), best way to handle it would probably be to return the string query and a list of all the arguments in order. Then we can deconstruct that list to pass as the arguments to the knex query

2023-02-06 22:52 UTC, manaswi223 commented
So to answer Marc's comment:

I think to prevent sql injection situations, as Marc mentioned, we can parameterize the query like:
while using any knex method, for example: `.whereRaw` here:

```
knex.select().from('employee_details').whereRaw(`column = ? `, [rdsExpression]).then(rows => {
            console.log(rows);
});
```

this can separate the actual sql query from the "data" & hence, prevent any malicious sql injection

2023-02-09 19:35 UTC, manaswi223 commented
closing this in favor of #1236

2023-02-09 19:35 UTC, closed without merging