feat(datastore-filters): add filters for DataStore properties
aws-amplify/amplify-category-api pull request #1382
Opened 2023-04-03 14:24 UTC by MorCohenAres

#### Description of changes

Added `_version`, `_deleted`, `_lastChangedAt` fields to the generated `ModelXXXFilterInput` so people can query the API without the deleted items, for example.

##### CDK / CloudFormation Parameters Changed

None.

#### Issue #, if available

Implemented #78.

I noticed that people are actively asking in the thread to implement the feature, but wasn't sure why it hasn't been implemented yet.
If there's a special reason or an intentional decision not to implement it (or not do it that way), please let me know.

#### Description of how you validated changes

1. Created an example `Todo` model that has the list/sync query, pushed it and made sure the filter applies in the AppSync console
2. Created the `Todo` model without sync or list, but connected it to another model (`ListOfTodos`) with an `@hasMany` directive. Pushed and made sure the query for `Todo`s through `ListOfTodos` has these fields and that they're working.

#### Checklist

- [X] PR description included
- [X] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-04-11 18:09 UTC, phani-srikar reviewed
Changes look good to me. Only callout is to add some unit and possibly e2e test to modified behavior.

2023-04-11 19:06 UTC, iartemiev requested changes
Thanks for opening the PR, @MorCohenAres. 

I see the value in adding the `_deleted` field to the list query filter input specifically. What are the use cases that justify adding `_version` and `_lastChangedAt` as well?

I think that if we make this change, it should only apply to the list query filter input, not the sync query, as DataStore relies on these internal fields and filtering on them can lead to unexpected behavior when using DataStore specifically.

2023-04-19 21:57 UTC, MorCohenAres commented
@phani-srikar @iartemiev 
Thank you guys!

1. I added it to the tests :)
2. > I see the value in adding the _deleted field to the list query filter input specifically. What are the use cases that justify adding _version and _lastChangedAt as well?

Giving it a second thought, I think you're right. I narrowed it down to only have the `_deleted` field as a possible filter.

3. > I think that if we make this change, it should only apply to the list query filter input, not the sync query, as DataStore relies on these internal fields and filtering on them can lead to unexpected behavior when using DataStore specifically.

That might be correct. However, the problem with it is that `Sync`, `List` and `Get` queries, all use the same `ModelXXXFilterInput` object.
Making a new separation to declare a new filter object, and testing it well, might be unworthy and significantly larger than the scope that this PR aims to address.

If that's OK with you, my opinion is that this scope should stay narrow. Let me know if you strongly disagree...

Please feel free to review this once again 😄

2023-04-24 17:04 UTC, iartemiev commented
@MorCohenAres thank you for making the requested changes.

On the last point - I agree that creating a new filter input object will result in a bigger code change, but I think it's worth it in this case, because it will serve as a guardrail to prevent unintended API use. It's never valid to filter on `_deleted` when using DataStore, so we don't want to implicitly encourage that by exposing that field in the filter input for sync queries. 

Please let us know if you need assistance from the team with this change. We'd be happy to build on top of your PR if that's the case.

2023-04-25 11:31 UTC, MorCohenAres commented
@iartemiev Thank you for your comment!
I have made the necessary changes and created a new `ModelSyncXXXFilterInput` type.

Actually it really wasn’t that hard, because of the already-existing separation between `Query` and `Subscription` which we can take influence from.
Also the code in those areas is nice and clean, very comfortable to work with :)

So I updated the tests as well, and you're welcome to review it again.

**NOTE**: 
I'm using the new `ModelSyncXXXFilterInput` only at the sync query level.
In nested fields inside the sync query it's still uses the regular `ModelXXXFilterInput`. This is because the main list of items that is returned from the sync query is the part that requires you not to filter by `_deleted` so you can align your local database with the deleted items. Nested lists of items are not used for this purpose (If you want to sync the nested type you should use the corresponding sync query), so they should use the regular filter.

Please let me know what you think!

2023-04-25 17:29 UTC, phani-srikar requested changes
Changes look good. Can you please run `yarn refresh-lockfile` from the root of the repository so that the `yarn.lock` is refreshed? This command basically just deletes the `yarn.lock` file and regenerates it using `yarn` command. Before pushing your change you can verify if the file is up-to date using `yarn verify-yarn-lock` from the repo root.

2023-04-26 00:23 UTC, MorCohenAres commented
@dpilch @phani-srikar Fixed `yarn.lock`. Thanks!

2023-04-26 14:42 UTC, dpilch approved these changes

2023-04-26 15:03 UTC, phani-srikar submitted a review, later dismissed

2023-04-26 15:59 UTC, dpilch approved these changes

2023-04-26 18:42 UTC, phani-srikar submitted a review, later dismissed

2023-04-26 18:54 UTC, iartemiev submitted a review, later dismissed

2023-04-26 19:52 UTC, MorFix commented
Thank you for your approvals. Would love to contribute more in the future! ☺️

2023-04-26 19:54 UTC, MorCohenAres commented
Thank you for your approvals.
Would love to contribute more in the future! ☺️

2023-04-26 20:23 UTC, phani-srikar commented
Running e2e tests on this. [Follow link if you've access](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/5962/workflows/18ab9013-8418-40b5-8fd2-054263fd49d7)

2023-04-27 00:48 UTC, MorCohenAres commented
> Running e2e tests on this. [Follow link if you've access](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/5962/workflows/18ab9013-8418-40b5-8fd2-054263fd49d7)

I see that [it failed](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/5962/workflows/1d3af334-fdb8-4078-bea4-5f3d1663f79c/jobs/119117/tests#failed-test-0) bcause of renaming the sync filter input. I have now fixed it.

BUT I'm now realizing that **THIS IS A BREAKING change** for client Amplify SDKs.

For example [here](https://github.com/aws-amplify/amplify-swift/blob/fc9004077a24b7cb52d901c168099d73d1d2d00f/AmplifyPlugins/Core/AWSPluginsCore/Model/Decorator/FilterDecorator.swift#L38) We'll need to change this manually-generated filter name to support!

Same [Here](https://github.com/aws-amplify/amplify-js/blob/268a270a2810a43a8361cbe5c6b02cd2a1f419dd/packages/datastore/src/sync/utils.ts#L360) (JS) and [Here](https://github.com/aws-amplify/amplify-android/blob/3423d4cad9a5f001d24cbec7c364c5be055596a7/aws-datastore/src/main/java/com/amplifyframework/datastore/appsync/AppSyncRequestFactory.java#L145) (Android), and also make sure it works in Flutter.
This should be taken into consideration when people upgrade their CLI with these changes. How should we tackle this?

2023-04-27 16:28 UTC, iartemiev commented
@MorCohenAres - you're right, I didn't account for that with the approach I suggested. With that being said, let's revert back to what you had before: a single Input type with `_deleted` added. That way the change will be non-breaking across the platforms . Apologies for the back and forth.

2023-04-27 16:55 UTC, sundersc commented
Will adding the filter `_deleted = 0` by default to the `Get` and `List` (when DS enabled) DDB query filter expression address the usecase?

2023-04-28 20:28 UTC, iartemiev commented
@MorCohenAres - we discussed this amongst the team and would like to go with the original approach you had - single Input object that's shared across the 3 Query fields. Thanks!

2023-04-30 00:00 UTC, MorFix commented
(It's me, Mor. I just abandoned the old account)
@iartemiev OK thank you guys. I have now updated everything according to your latest decision.
Let's try e2e again to see if that works? 😄

2023-05-01 14:47 UTC, dpilch approved these changes

2023-05-01 15:16 UTC, iartemiev approved these changes

2023-05-01 16:26 UTC, phani-srikar commented
Follow [this link](https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api/6048/workflows/72869782-6b93-457c-84c3-bcc11ba816e4) for latest e2e.

2023-05-01 16:27 UTC, phani-srikar approved these changes

2023-05-01 17:51 UTC, phani-srikar commented
The `schema-predictions` test failure is a known issue which will be fixed when we re-run the pipeline against latest CLI version.

2023-05-02 09:42 UTC, MorFix commented
> The `schema-predictions` test failure is a known issue which will be fixed when we re-run the pipeline against latest CLI version.

Then is it ready to be merged? Are we holding it till the CLI updates in the pipeline?

2023-05-02 17:11 UTC, merged

2023-05-02 17:12 UTC, phani-srikar commented
Thanks for the contribution @MorFix. We will keep you updated once this change makes it to Amplify CLI release.

2023-05-08 15:42 UTC, offlineprogrammer commented
@MorCohenAres Thank you for your contribution! I would like to follow up with you on this. can you please connect with me on [Twitter](https://twitter.com/_Mo_Malaka_) or [LinkedIn](https://www.linkedin.com/in/momalaka/)