refactor: remove ttl override from context
aws-amplify/amplify-category-api pull request #1558
Opened 2023-06-09 14:44 UTC by dpilch

#### Description of changes

* Remove ttl override from context. 
* Set ttl value in stash with lazy ref.

##### CDK / CloudFormation Parameters Changed
N/A

#### Issue #, if available
N/A

#### Description of how you validated changes

* Unit tests
* E2E tests: https://app.circleci.com/pipelines/github/aws-amplify/amplify-category-api?branch=run-e2e/dppilche/ttl

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-09 19:46 UTC, alharris-at submitted a review, later dismissed

2023-06-12 17:53 UTC, AaronZyLee requested changes
The sync e2e test failed and the error seems related to the VTL error. Could you double check it? 
<img width="909" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/20614187/75c1d80b-d685-4951-bca7-0edbd0561a6e">

2023-06-12 18:00 UTC, dpilch commented
Oops, appears to be missing closing parentheses!

2023-06-12 18:07 UTC, phani-srikar commented
Easily slipped my eyes while reviewing the snapshots.

2023-06-12 19:48 UTC, AaronZyLee approved these changes

2023-06-12 20:18 UTC, alharris-at approved these changes

2023-06-12 20:19 UTC, merged