chore: remove git webhook
aws-amplify/amplify-category-api pull request #1570
Opened 2023-06-13 22:51 UTC by AaronZyLee

#### Description of changes

##### CDK / CloudFormation Parameters Changed

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2023-06-15 16:22 UTC, dpilch requested changes

2023-06-15 16:22 UTC, dpilch commented on scripts/cloud-utils.sh
> +    mwinit
When off VPN `--aea` flag is need to successfully authenticate. It doesn't appear to have ill effects to have this flag when on VPN, so best to add for convenience. 

```suggestion
    mwinit --aea
```

2023-06-15 17:47 UTC, dpilch submitted a review, later dismissed

2023-06-16 00:27 UTC, phani-srikar submitted a review, later dismissed

2023-06-19 17:29 UTC, phani-srikar approved these changes

2023-06-19 17:34 UTC, merged