Gql preprocess
aws-amplify/amplify-category-api pull request #20
Opened 2022-05-06 00:37 UTC by marcvberg

#### Description of changes
This begins to add support for transformer plugins to modify schemas outside the transformation process. Enables codegen to hook into these changes directly and use them

This is only for the purpose of adding support in right now and does not hook into any active workflows

#### Issue #, if available

#### Description of how you validated changes
Unit testing

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-05-26 17:04 UTC, marcvberg commented on packages/amplify-graphql-transformer-core/src/transformation/transform.ts
> +        processedSchema = JSON.parse(JSON.stringify(transformer.mutateSchema(context)));
Using it as a deep copy - there are apparently some portions of the `DocumentNode` types that are not readonly, so the result which ImmerJS was producing was completely readonly and prevents the schema from being `print`ed by the `graphql` library, which will end up breaking parts of our code down the line

2022-05-26 17:05 UTC, marcvberg commented on packages/amplify-data-core/src/amplify-data-api.ts
> +  private schema?: DocumentNode;
Resolving as I deleted this code and will implement single-read differently in a different PR

2022-05-26 17:06 UTC, marcvberg commented on packages/amplify-graphql-transformer-core/src/transformation/transform.ts
> +    let context = new TransformerPreProcessContext(schema, this?.options?.featureFlags);
We'd have to write our own merging code to do that right? To take a number of processed schema outputs and convert them to one fully processed schema?

2022-05-27 14:18 UTC, marcvberg commented on packages/amplify-graphql-transformer-core/src/transformation/transform.ts
> +    });
Done

2022-05-27 14:29 UTC, marcvberg commented on packages/amplify-graphql-transformer-core/src/transformation/transform.ts
> +    let context = new TransformerPreProcessContext(schema, this?.options?.featureFlags);
Resolved - recreating context through reduce

2022-05-27 15:09 UTC, marcvberg commented on packages/amplify-graphql-transformer-core/src/transformation/transform.ts
> +   * @param schema A parsed GraphQL DocumentNode
Updated docstring with some more detail

2022-06-02 22:30 UTC, alharris-at submitted a review, later dismissed

2022-06-08 22:38 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/__tests__/amplify-graphql-has-one-transformer.test.ts
> +          }
Nit: Is it possible to reduce the nesting here using `filter` and `some`?
May be like `doc.definitions.filter(def => (def.kind === '' and so on) && def.fields.some(f => f.name.value === fieldName))`.

2022-06-08 22:41 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/graphql-belongs-to-transformer.ts
> +          });
Same as above. Please see if nesting can be reduced using filter and some.

2022-06-08 22:43 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/graphql-has-many-transformer.ts
> +      });
Can we use `filter` instead of foreach and if?

2022-06-08 22:44 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/graphql-has-one-transformer.ts
> +            });
Same as the previous comment. Please see if we can use filter to simply the logic.

2022-06-08 22:45 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/graphql-many-to-many-transformer.ts
> +      });
Consider use of filter.

2022-06-08 22:46 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/schema.ts
> +}
missing semicolon.

2022-06-08 22:48 UTC, sundersc commented on packages/amplify-graphql-relational-transformer/src/schema.ts
> +}
missing semicolon.

2022-06-08 22:50 UTC, sundersc reviewed
Left few comments to check whether the nested foreach and if statements can be avoided using filter method. Otherwise the changes look good.

2022-06-11 05:48 UTC, sundersc submitted a review, later dismissed
LGTM

2022-06-13 15:49 UTC, alharris-at requested changes

2022-06-13 15:58 UTC, alharris-at approved these changes

2022-06-13 16:02 UTC, merged