feat(generate-schema): custom ssl cert support to generate schema command
aws-amplify/amplify-category-api pull request #2615
Opened 2024-06-10 18:19 UTC by sundersc

#### Description of changes

Adds support to accept custom ssl certificate to typescript data schema generation.

##### CDK / CloudFormation Parameters Changed

NA

#### Issue #, if available
NA

#### Description of how you validated changes
- Added unit tests.
- Manual tests

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-06-10 19:22 UTC, sundersc commented on packages/amplify-graphql-schema-generator/API.md
> -
Currently outside of API repo, Gen2 generate command is the only package that relies on this package. Generate command doesn't use this interface so it is safe to remove it. Same for the `PostgresDataSourceConfig`.

2024-06-11 19:42 UTC, phani-srikar approved these changes

2024-06-14 17:50 UTC, palpatim requested changes

2024-06-14 17:50 UTC, palpatim commented on packages/amplify-graphql-schema-generator/API.md
> +    sslCertificateSecrteName?: string;
```suggestion
    sslCertificateSecretName?: string;
```

2024-06-14 21:06 UTC, phani-srikar approved these changes

2024-06-17 21:08 UTC, palpatim approved these changes

2024-06-17 23:34 UTC, merged