feat(conversation): update directive input for tool definition for model list queries
aws-amplify/amplify-category-api pull request #3013
Opened 2024-11-12 02:26 UTC by atierian

#### Description of changes

##### CDK / CloudFormation Parameters Changed

#### Issue #, if available

#### Description of how you validated changes

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] E2E test run linked
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies
- [ ] Any CDK or CloudFormation parameter changes are called out explicitly

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2024-11-12 23:49 UTC, palpatim approved these changes
Does the validation allow for mixed-mode tool maps? In other words, the map contains both a `queryName` style and a `modelOperation style?` (I can’t think of why this would be necessary, but if it’s supported, we should test it)

Approved assuming the answer is "no", or that we'll add tests for mixed-mode support later.

Also approved as API BR since this is a change to the conversation directive API.

2024-11-13 00:09 UTC, atierian commented
> Does the validation allow for mixed-mode tool maps? In other words, the map contains both a `queryName` style and a `modelOperation style?` (I can’t think of why this would be necessary, but if it’s supported, we should test it)

A single tool definition cannot have both `queryName` (custom operation) and `modelName` / `modelOperation` (model generated query). This is validated here [[1](https://github.com/aws-amplify/amplify-category-api/pull/3013/files#diff-85826cdebb41acdefde0112b9171f40669a7de1dc7db6773054f891a2ba67966R196-R198), [2](https://github.com/aws-amplify/amplify-category-api/pull/3013/files#diff-6c75cd673bd6f6dbd63c98f54181a1800e9c2038244d5b64828a0d5e0f92ba45R25-R29)].

But a single `@conversation` can have multiple tools, which can be mixed. I thought I added a test case for that, but looking again, I only added one in [data-schema](https://github.com/aws-amplify/amplify-api-next/pull/390/files#diff-77c9378ad1789fdac5998491f0d47d14b34507ee7a84e7afa9f07fad007699c2R908-R923), which doesn't cover everything we'd get with a test here.

> Approved assuming the answer is "no", or that we'll add tests for mixed-mode support later.

If I need to make any other changes to this branch before merging, I'll include a test case for mixed tool definitions. Otherwise, I'll include it in a follow up.

2024-11-13 18:14 UTC, phani-srikar requested changes

2024-11-13 18:14 UTC, phani-srikar commented on packages/amplify-graphql-conversation-transformer/src/tools/process-tools.ts
> +  return listQueryArgument ?? `list${pluralize(toUpper(modelName))}`;
For constructing the list query name consistently between this and model transformer, recommend using `getFieldNameFor('list', modelName)` that is exported from the transformer core - https://github.com/aws-amplify/amplify-category-api/blob/acc8140c323988da595630ed9c047e03a825635f/packages/amplify-graphql-transformer-core/src/utils/operation-names.ts#L26

2024-11-13 18:50 UTC, phani-srikar approved these changes

2024-11-13 19:18 UTC, atierian commented
The failing test is `verify_amplify_backend_compatability` because this branch isn't up to date with `main`. It's not related to these changes.

2024-11-13 19:39 UTC, merged