fix(amplify-graphql-auth-transformer): initial commit without FF
aws-amplify/amplify-category-api pull request #580
Opened 2022-06-21 16:28 UTC by phani-srikar

#### Description of changes
The Auth checks in a `create` mutation currently do not set the `ownerField` if the `@model` type has both static group auth and owner auth rules specified on it and the user is successfully authorized via static auth checks. This is reported by customers as a regression from `V1` behavior. 

This PR fixes this issue behind a FF `populateOwnerFieldForStaticGroupAuth` which is set to `false` for existing projects, `true` otherwise. FF PR in CLI repo: https://github.com/aws-amplify/amplify-cli/pull/10630

**Behavioral changes**
When the above FF is `true`, we automatically set the value of `ownerField` if the user is authorized via static group checks in a `create` mutation. This means that if the user is removed from the group, he will still continue to have access to the records he created since he is the owner.

#### Issue #, if available

https://github.com/aws-amplify/amplify-category-api/issues/37

#### Description of how you validated changes
Unit tests: Updated screenshots indicate the change

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-06-22 21:39 UTC, danielleadams requested changes
@phani-srikar Looks good - I think it would be good to add a test scenario with the `AllThree` model too to test `[String]` type in the e2e.

2022-06-22 21:39 UTC, danielleadams commented on packages/amplify-graphql-auth-transformer/src/resolvers/helpers.ts
> +export const populateOwnerField = (
I think that this field should be something like `generatePopulateOwnerField` so that it's clear that it's generating VTL code.

2022-06-24 16:14 UTC, danielleadams submitted a review, later dismissed

2022-06-27 22:43 UTC, AaronZyLee reviewed
Overall LGTM. Just have one question on the missing scenario in the tests where a user is not authorized by a group but creates an entry where the `owner` is not specified, which results in `sub::username` as the `owner` field.

2022-06-28 01:31 UTC, phani-srikar commented
@AaronZyLee added a check in an e2e test

2022-06-28 17:12 UTC, AaronZyLee reviewed
Could you also check the `AllThree` schema with scenario where the owner is not defined in input and the mutation is done by none-admin owner? This case is special because the owner is defined as `[String]`. The current cases only include explicit `owner` in input or `owner = null`. Not sure the latter one is similar to the implicit input case.

2022-06-30 15:10 UTC, danielleadams submitted a review, later dismissed

2022-07-05 17:55 UTC, alharris-at approved these changes

2022-07-05 18:50 UTC, danielleadams commented
@phani-srikar I think this needs a rebase. There are commits in this PR that I think are from a previous version of `main`

2022-07-06 00:19 UTC, merged