Dynamic group subscriptions
aws-amplify/amplify-category-api pull request #933
Opened 2022-10-27 12:57 UTC by marcvberg

#### Description of changes
Add support for dynamic groups in subscriptions with enhanced filtering

#### Issue #, if available

#### Description of how you validated changes
E2E, unit, manual testing

#### Checklist

- [ ] PR description included
- [ ] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-10-27 17:22 UTC, AaronZyLee commented on packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
> +
The unit test block is missing

2022-10-27 17:22 UTC, AaronZyLee commented on packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsRuntimeFiltering.e2e.test.ts
> +    subscription = observer.subscribe(
nit: We can also add a test for non-list type dynamic auth since we use different filters (`in` or `containsAny`)

2022-10-27 17:53 UTC, phani-srikar requested changes
Can you please rebase with `main` to resolve the publish error in checks? Thanks.

2022-10-27 17:53 UTC, phani-srikar commented on packages/amplify-graphql-auth-transformer/src/__tests__/group-auth.test.ts
> +
Did you want to add more tests here or just an empty block?

2022-10-27 17:53 UTC, phani-srikar commented on packages/graphql-transformers-e2e-tests/src/__tests__/SubscriptionsRuntimeFiltering.e2e.test.ts
> +    subscription = observer.subscribe(
Can we add couple more e2es around:
1. If I am not part of the Dynamic group, I shouldn't be allowed to subscribe.
2. If I have a filter input in addition to dynamic group auth, we appropriately filter the subscriptions.

2022-11-01 22:36 UTC, alharris-at commented
Closing this PR in favor of https://github.com/aws-amplify/amplify-category-api/pull/944, which is on a branch multiple folks on the team can iterate on.

2022-11-01 22:36 UTC, closed without merging