Feat/graph ql transformer core added bracket mismatch detection
aws-amplify/amplify-category-api pull request #974
Opened 2022-11-09 16:07 UTC by ncarvajalc

#### Description of changes

Added bracket validation for graphQL schema.
Added custom error for bracket mismatch.

This was necessary as the `parse` function from the graphql dependency doesn't tell much about the error and it isn't clear it is because of a bracket mismatch.

Error without the changes: 
```bash
🛑 Syntax Error: Expected Name, found {
``` 

Error after the changes:
```bash
🛑 Syntax Error: mismatched brackets found in the schema. Unexpected )
```
or
```bash
🛑 Syntax Error: mismatched brackets found in the schema. Missing )
```

#### Issue #, if available
#107

#### Description of how you validated changes

`yarn test` passing and used custom app with `amplify-dev` to see the newly thrown errors when there is a bracket mismatch.

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [ ] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-10 20:19 UTC, phani-srikar requested changes
Can you please add a few test cases covering some edge cases like:
- Empty schema i.e '' is handled.
- Schema with mismatched brackets throws appropriate error.
- Schema with correct brackets does not throw.
Thanks

2022-11-10 20:19 UTC, phani-srikar commented on packages/amplify-category-api/src/graphql-transformer/sandbox-mode-helpers.ts
> +        if (c !== stack.pop()) {
I like how you used the fallthrough case statements.

2022-11-10 20:19 UTC, phani-srikar commented on packages/amplify-category-api/src/graphql-transformer/sandbox-mode-helpers.ts
> +        break;
Can we use similar fallthrough like you used below to say `stack.push(c)` once?

2022-11-15 18:13 UTC, ncarvajalc commented
@phani-srikar with @jcollinc we made the changes you requested. Hope it gets merged soon :D

2022-11-15 18:49 UTC, phani-srikar approved these changes
LGTM. Thanks!

2022-11-15 19:07 UTC, alharris-at commented
Hey @ncarvajalc - I see a bunch of `yarn.lock` updates that don't seem related to this change. (Probably related to running `setup-dev`. Could you `rm` that file and just run `yarn` in the root directory to rebuild?

2022-11-15 19:08 UTC, alharris-at reviewed
LGTM - just left one comment about the `yarn.lock` update.

2022-11-16 17:35 UTC, ncarvajalc commented
@alharris-at with @jcollinc we added the line where the bracket mismatch is occurring. Let me know what you think.

2022-11-16 20:08 UTC, alharris-at approved these changes

2022-11-16 20:17 UTC, alharris-at requested changes
Discussed offline, as implemented this will currently throw an error on a comment which has a mismatch brace in it, which constitutes a breaking change for customers.

Previously this line would have been part of a legal schema, but now would now.

```graphql
# This is my type that has some parameters :)
```

Recommend switching the response to a warning instead of an exception.

2022-11-17 17:49 UTC, ncarvajalc commented
@alharris-at with @jcollinc we successfully solved the issue we had and now it doesn't consider comments or strings for the bracket check, as there can be cognito group names with hashes and brackets in it. Now this is valid:
`# This is my type that has some parameters :)`
And also this:
```graphql
@auth(
    rules: [
      {
        allow: owner
        groups: ["Admins#(accounts):)"]
        operations: [create, update, delete]
      }
      { allow: public, operations: [read] }
    ]
  ) 
```

2022-11-22 17:19 UTC, alharris-at approved these changes

2022-11-22 18:02 UTC, AaronZyLee reviewed
The change overall LGTM. Left some comments below.

- By removing `yarn.lock` it means removing them in the git commit. Sorry for the confusion.

2022-11-22 19:33 UTC, alharris-at commented
Closing in favor of https://github.com/aws-amplify/amplify-category-api/pull/1020

2022-11-22 19:33 UTC, closed without merging