refactor: use envParamManager instead of reading TPI file
aws-amplify/amplify-category-api pull request #984
Opened 2022-11-11 18:58 UTC by jhockett

#### Description of changes
- Replaced all cases where the `team-provider-info.json` file was being read from and written to with parameter manager from `@aws-amplify/amplify-environment-parameters`
- Various lint fixes

#### Description of how you validated changes

#### Checklist

- [x] PR description included
- [ ] `yarn test` passes

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-14 20:09 UTC, edwardfoyle commented on packages/amplify-category-api/src/index.ts
> +  if (resourceParamManager.getParam(rdsRegion)) {
I think a better check here would be `(await ensureEnvParamManager()).instance.hasResourceParamManager(category, resourceName)` then get the param manager inside the if statement

2022-11-14 22:02 UTC, sobolk submitted a review, later dismissed

2022-11-15 17:05 UTC, edwardfoyle submitted a review, later dismissed

2022-11-29 22:52 UTC, phani-srikar requested changes

2022-11-29 22:52 UTC, phani-srikar commented on packages/amplify-category-api/src/index.ts
> +  if (envParamManager.hasResourceParamManager(category, resourceName)) {
The only difference I see from the previous case is that we were checking for existence of `rdsRegion` parameter. Is it possible to add that check?

2022-12-06 18:05 UTC, phani-srikar approved these changes

2022-12-06 18:55 UTC, edwardfoyle approved these changes

2022-12-06 21:50 UTC, merged