fix: 🐛 VTL issue when field starts with an underscore
aws-amplify/amplify-category-api pull request #996
Opened 2022-11-15 14:35 UTC by ncarvajalc

Fixed Mapping Template Lexical AppSync error when using field level auth rules with fields starting with an underscore

✅ Closes: #735

#### Description of changes

Changed `context.source.${fieldName}` to `context.source["${fieldName}"]`.

#### Issue #, if available

Closes: #735

#### Description of how you validated changes

Changed tests to new generated vtl templates and tested in in custom app 

#### Checklist

- [x] PR description included
- [x] `yarn test` passes
- [x] Tests are [changed or added](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#tests)
- [ ] Relevant documentation is changed or added (and PR referenced)
- [ ] New AWS SDK calls or CloudFormation actions have been added to relevant test and service IAM policies

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2022-11-16 20:21 UTC, alharris-at approved these changes

2022-11-16 20:28 UTC, AaronZyLee requested changes
Thanks for the contribution. Could you remove the change for `yarn.lock`? Otherwise LGTM

2022-11-16 21:08 UTC, ncarvajalc commented
@AaronZyLee @alharris-at I just deleted the yarn.lock file.

2022-11-22 19:33 UTC, alharris-at commented
Closing in favor of https://github.com/aws-amplify/amplify-category-api/pull/1020

2022-11-22 19:33 UTC, closed without merging